## Serverless Framework é uma ferramenta que automatiza o provisionamento de recursos em um cloud provider

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

service: golang-serverless

frameworkVersion: '3'

# inicio da configuração do localstack
custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    endpointFile: .localstack/resources/localstack_endpoints.json
    lambda:
      mountCode: False
    deploymentBucket:
      name: serverless

# inicio da configuração do cloud provider que será utilizado
provider:
  name: aws
  runtime: go1.x
  stage: local
  region: us-east-1
  environment:
    DYNAMODB_TABLE: Products
  # definindo as permissões na aws
  iam:
    role:
      statements:
        # permitindo a leitura e escrita no dynamo
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          # informa como o serviço do dynamo é identificado na aws
          Resource: # vai criar automáticamente o resource do dynamo lá na aws se ele não existir
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

package:
  patterns:
    - '!./**'
    - ./bin/**

# inicio da configuração das functions e como elas serão executadas
functions:
  # define o nome da lambda
  insert:
    # caminho até o binário a ser executado
    handler: bin/InsertProduct
    # configuração de quais eventos que devem disparar a execução da lambda
    events:
      # configura APIGateway para tratar que todo request POST no /products execute a lambda de cadastro
      - http:
          path: /products
          method: post

  # define o nome da lambda
  list:
    handler: bin/ListProducts
    events:
      # configura APIGateway para tratar que todo request GET no /products execute a lambda de listagem
      - http:
          path: /products
          method: get
  
# inicio da configuração dos recursos na cloud
resources:
  Resources:
    # configurando a criação automática da tabela do dynamo na aws
    Products:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1